### PR TITLE
New : function to clear message queue

### PR DESCRIPTION
**Pull request by ameisso**
This is a proposal 

In my usage, I sometimes need to send a message with a very high priority (security handbrake). 
So clearing the queue helps doing this.

Best

### CODE REVIEW

**Comment by Miq1** [comment]
I like the idea and your solution looks good. The only thing I would like to add is the same function for the TCP clients as well.

**Review by Miq1 — APPROVED** [review]
Wonderful, thank you!

**Comment by ameisso** [comment]
Hello, 

Thanks for your feedback 
I've made the changes. it compiles, but I have nothing to test ATM 

Best

**Comment by Miq1** [comment]
I will be able to test tomorrow.

**Comment by sdrshnptl** [comment]
strong feeling that this is a solution to a problem I've encountered recently.
My esp32 on the w5500 modbus server is crashing without cause.
Will validate and update status.
Thanks!

**Pull request merged**
